createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: team
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"clickupTeam"'
          properties:
            url: .id | "https://app.clickup.com/" + . + "/v/o/s/default_space"
            members: .members[].email
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"clickupProject"'
          properties:
            url: .id | "https://app.clickup.com/t/" + .
            startDate: .start_date | tonumber | todate
            endDate: .end_date | tonumber | todate
            totalIssues: .issue_count
          relations:
            team: .team_id
  - kind: issue
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .id
          title: .name
          blueprint: '"clickupIssue"'
          properties:
            url: .url
            description: .description
            status: .status.status
            assignee: .assignees[0].email
            creator: .creator.email
            priority: .priority.priority | tostring
            created: .date_created | todate
            updated: .date_updated | todate
          relations:
            project: .project.id
